version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"  # React will run on port 80 for Render
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=/predict  # if backend is reverse-proxied

  backend:
    build: ./backend
    expose:
      - "5000"  # only internal access
    depends_on:
      - mongo
      - ml_model
    environment:
      - MONGO_URI=mongodb://mongo:27017/thyroid
      - FLASK_API_URL=http://ml_model:5000/predict

  ml_model:
    build: ./ml_model
    expose:
      - "5000"  # only internal access

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
