services:
  - type: web
    name: thyrolead
    env: docker
    plan: free
    region: singapore
    repo: https://github.com/manaswini79/thyroid
    branch: main
    dockerComposeFile: docker-compose.yml
    dockerContext: .
    autoDeploy: true
