version: "1"

services:
  - type: web
    name: thyrolead
    env: docker
    repo: https://github.com/manaswini79/thyroid
    branch: main
    plan: free
    region: singapore
    dockerContext: .
    dockerComposeFile: docker-compose.yml
    autoDeploy: true
